### ISSUE TITLE
AttributeError: 'UNetSpatioTemporalConditionModel' object has no attribute 'module'. Did you mean: 'modules'?

### ISSUE THREAD

**Issue by BlakeOne** [pixeli99/SVD_Xtend#2]
Hey there, I'm trying out your new training script but I get this error... I'm using stabilityai/stable-video-diffusion-img2vid for the pretrained_model_name_or_path BTW but I'm not sure if that's correct?

AttributeError: 'UNetSpatioTemporalConditionModel' object has no attribute 'module'. Did you mean: 'modules'?

**Comment by pixeli99** [comment]
https://github.com/pixeli99/SVD_Xtend/blob/64c9783a8fabaedab6e4a667abe2d44629e62579/train_svd.py#L940

change to
```python
passed_add_embed_dim = unet.config.addition_time_embed_dim * len(add_time_ids)
expected_add_embed_dim = unet.add_embedding.linear_1.in_features
```
You just need to delete these two lines of modules, it's due to the unfriendliness on my code because I'm using multi-GPU training, and this problem occurs under ddp mode. If you are using a single GPU, you can simply delete them.

**Comment by BlakeOne** [comment]
Thanks removing those lines fixed it for me. :)
